spring.application.name=demo
server.port=8081
# H2データベースのURL (メモリ上での保存の場合)
#spring.datasource.url=jdbc:h2:mem:testdb
# H2データベースのURL (ファイルベースの保存の場合)
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# H2 Console (ブラウザでのDB閲覧ツール) を有効にする場合
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JPAに関する設定
#起動時に作成、停止時に削除する
#spring.jpa.hibernate.ddl-auto=create-drop
#ない場合は作成、あればそのまま
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
